# Manipulção de Strings com Python

> Uma varivel primaria de texto é chamada de char ou caracter possibilitando o armazenamento de 8 bit de memória. Quando necessitamos de um conjunto de caracteres utilizamos um objeto, ou variaveis compostas no caso da maioria das linguagens chamada de string. Vamos ver como se aplica

In [18]:
frase = "Boa tarde a todos"
print(frase)
saudacao = frase [0:9]
print(saudacao)

Boa tarde a todos
Boa tarde


In [19]:
print(type(frase))
print(type(saudacao))

<class 'str'>
<class 'str'>


In [20]:
print(frase.count('t'))
print(saudacao.count(' '))


2
1


In [21]:
print(len(frase))
print(len(saudacao))

17
9


In [22]:
frase = frase.replace('a todos','galerinha!')
print(frase)
saudacao = saudacao.replace ('tarde','noite')
print(saudacao)

Boa tarde galerinha!
Boa noite


In [23]:
frase = [i for i in frase]
print(frase)

['B', 'o', 'a', ' ', 't', 'a', 'r', 'd', 'e', ' ', 'g', 'a', 'l', 'e', 'r', 'i', 'n', 'h', 'a', '!']


In [24]:
for x in frase:
    print(x)

B
o
a
 
t
a
r
d
e
 
g
a
l
e
r
i
n
h
a
!


## Exercício 1

> Crie um código para a seguinte frase:"Sabia que o sabiá sabia assubiar" reparticionado por espaço, após isso crie um print format para visualizar cada palavra em uma coluna separada.

In [25]:
#metodo split
frase = "Sabia que o sabiá sabia assubiar"

palavras = frase.split()

print(palavras)

for i in range(max(len(x)for x in palavras)):
    for y in palavras:
        print(y[i] if i < len(y) else ' ', end =' ')

    print()


['Sabia', 'que', 'o', 'sabiá', 'sabia', 'assubiar']
S q o s s a 
a u   a a s 
b e   b b s 
i     i i u 
a     á a b 
          i 
          a 
          r 


In [26]:
#segundo metodo, usando "join" para fazer espaçamentos e separação
# ' '.join responsavel pelo espaçamento 
for i in range(max(len(x) for x in palavras)):
    print(' '.join(x[i] if i < len(x) else ' ' for x in palavras))

S q o s s a
a u   a a s
b e   b b s
i     i i u
a     á a b
          i
          a
          r


# Introudução a Numpy

> Numpy é uma biblioteca python para desenvolvimento de matrizes. Tem por objetivos facilitar na criação de algoritmos matematicos para solucionar paradigmas avançados em relação a arrays.

In [27]:
import numpy as np 
a = np.array([1,2,3])
print(a)

[1 2 3]


In [28]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [29]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [30]:
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [34]:
#maximo
print(a.max())
print(b.max())
print(c.max())
print(d.max())

3
6
1.0
1.0


In [35]:
#minimo
print(a.min())
print(b.min())
print(c.min())
print(d.min())

1
1
1.0
0.0


In [37]:
#"sum" soma dos valores
print(a.sum())
print(b.sum())
print(c.sum())
print(d.sum())

6
21
9.0
5.0


In [38]:
#"mean" média
print(a.mean())
print(b.mean())
print(c.mean())
print(d.mean())

2.0
3.5
1.0
0.2


>Para desvio para padrão

In [42]:
#"round" arredondar
print(round(a.std(),2))
print(round(b.std(),2))
print(round(c.std(),2))
print(round(d.std(),2))

0.82
1.71
0.0
0.4


## Exercício 2

> Crie uma matriz chamada contar com os números de 0 até 9. Ao final crie uma contagem, média e desvio padrão dessa matriz. Para adicionar de zero a 9 utilize um for e depois atribua à matriz.

In [ ]:
#Igual o primeiro exercício(finalizar em casa)